services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sootio:latest
    container_name: sootio
    restart: always
    volumes:
      - sootio-data:/app/data
    networks:
      - proxy-net
    environment:
      - NODE_ENV=${NODE_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
      - ADDON_URL=${ADDON_URL}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - AD_API_KEY=${AD_API_KEY}
      - AD_CHECK_CONCURRENCY=${AD_CHECK_CONCURRENCY}
      - AD_CONCURRENCY=${AD_CONCURRENCY}
      - AD_MAX_RETRIES=${AD_MAX_RETRIES}
      - AD_RATE_PER_MINUTE=${AD_RATE_PER_MINUTE}
      - AD_RATE_PER_SECOND=${AD_RATE_PER_SECOND}
      - BATCH_SIZE=${BATCH_SIZE}
      - BITMAGNET_ENABLED=${BITMAGNET_ENABLED}
      - BITMAGNET_URL=${BITMAGNET_URL}
      - BLUDV_ENABLED=${BLUDV_ENABLED}
      - BTDIG_ENABLED=${BTDIG_ENABLED}
      - BTDIG_LIMIT=${BTDIG_LIMIT}
      - BTDIG_MAX_PAGES=${BTDIG_MAX_PAGES}
      - BTDIG_PROXY_URL=${BTDIG_PROXY_URL}
      - BTDIG_URL=${BTDIG_URL}
      - BTDIG_USE_PROXIES=${BTDIG_USE_PROXIES}
      - CACHE_BACKEND=${CACHE_BACKEND}
      - COMET_ENABLED=${COMET_ENABLED}
      - COMET_URL=${COMET_URL}
      - CUSTOM_HTML=${CUSTOM_HTML}
      - DEBRIDER_APP_API_KEY=${DEBRIDER_APP_API_KEY}
      - DEBRID_DEBUG_LOGS=${DEBRID_DEBUG_LOGS}
      - DEBRID_HTTP_PROXY=${DEBRID_HTTP_PROXY}
      - DEBRID_PER_SERVICE_PROXIES=${DEBRID_PER_SERVICE_PROXIES}
      - DEBRID_PROXY_SERVICES=${DEBRID_PROXY_SERVICES}
      - DEFAULT_DEBRID_SERVICE=${DEFAULT_DEBRID_SERVICE}
      - DISABLE_CACHE=${DISABLE_CACHE}
      - DISABLE_EARLY_RETURN=${DISABLE_EARLY_RETURN}
      - DISABLE_SEEK_VALIDATION=${DISABLE_SEEK_VALIDATION}
      - DISABLE_URL_VALIDATION=${DISABLE_URL_VALIDATION}
      - DISABLE_VIDEO_INDICATOR_FILTER=${DISABLE_VIDEO_INDICATOR_FILTER}
      - DIVERSIFY_CODECS_ENABLED=${DIVERSIFY_CODECS_ENABLED}
      - DOMAIN_CACHE_TTL_MS=${DOMAIN_CACHE_TTL_MS}
      - EARLY_EXIT_QUALITY_THRESHOLD=${EARLY_EXIT_QUALITY_THRESHOLD}
      - EARLY_RETURN_MIN_STREAMS=${EARLY_RETURN_MIN_STREAMS}
      - EARLY_RETURN_TIMEOUT_MS=${EARLY_RETURN_TIMEOUT_MS}
      - EASYNEWS_ENABLED=${EASYNEWS_ENABLED}
      - EASYNEWS_PASS=${EASYNEWS_PASS}
      - EASYNEWS_USER=${EASYNEWS_USER}
      - EXTTO_ENABLED=${EXTTO_ENABLED}
      - EXTTO_LIMIT=${EXTTO_LIMIT}
      - EXTTO_MAX_PAGES=${EXTTO_MAX_PAGES}
      - EXTTO_TIMEOUT=${EXTTO_TIMEOUT}
      - EXTTO_URL=${EXTTO_URL}
      - FLARESOLVERR_CIRCUIT_RESET_MS=${FLARESOLVERR_CIRCUIT_RESET_MS}
      - FLARESOLVERR_CIRCUIT_THRESHOLD=${FLARESOLVERR_CIRCUIT_THRESHOLD}
      - FLARESOLVERR_COOKIE_TTL_MS=${FLARESOLVERR_COOKIE_TTL_MS}
      - FLARESOLVERR_MAX_CONCURRENT=${FLARESOLVERR_MAX_CONCURRENT}
      - FLARESOLVERR_PER_IP_HOURLY_LIMIT=${FLARESOLVERR_PER_IP_HOURLY_LIMIT}
      - FLARESOLVERR_QUEUE_MAX_DEPTH=${FLARESOLVERR_QUEUE_MAX_DEPTH}
      - FLARESOLVERR_URL=${FLARESOLVERR_URL}
      - HOST=${HOST}
      - HTTP_HEADERS_TIMEOUT=${HTTP_HEADERS_TIMEOUT}
      - HTTP_KEEPALIVE_TIMEOUT=${HTTP_KEEPALIVE_TIMEOUT}
      - HTTP_MAX_CONNECTIONS=${HTTP_MAX_CONNECTIONS}
      - HTTP_MAX_HEADERS_COUNT=${HTTP_MAX_HEADERS_COUNT}
      - HTTP_RESOLVE_TIMEOUT=${HTTP_RESOLVE_TIMEOUT}
      - HTTP_TIMEOUT=${HTTP_TIMEOUT}
      - HUBCLOUD_USER_AGENT=${HUBCLOUD_USER_AGENT}
      - ILCORSARONERO_ENABLED=${ILCORSARONERO_ENABLED}
      - JACKETT_API_KEY=${JACKETT_API_KEY}
      - JACKETT_ENABLED=${JACKETT_ENABLED}
      - JACKETT_URL=${JACKETT_URL}
      - KNABEN_ENABLED=${KNABEN_ENABLED}
      - KNABEN_LIMIT=${KNABEN_LIMIT}
      - KNABEN_URL=${KNABEN_URL}
      - MAGNETDL_ENABLED=${MAGNETDL_ENABLED}
      - MAGNETDL_LIMIT=${MAGNETDL_LIMIT}
      - MAGNETDL_PROXY=${MAGNETDL_PROXY}
      - MAGNETDL_URL=${MAGNETDL_URL}
      - MAX_4KHDHUB_LINKS=${MAX_4KHDHUB_LINKS}
      - MAX_4KHDHUB_PROCESS=${MAX_4KHDHUB_PROCESS}
      - MAX_H264_RESULTS_PER_QUALITY=${MAX_H264_RESULTS_PER_QUALITY}
      - MAX_H265_RESULTS_PER_QUALITY=${MAX_H265_RESULTS_PER_QUALITY}
      - MAX_HUBCLOUD_BUTTONS=${MAX_HUBCLOUD_BUTTONS}
      - MAX_HUBCLOUD_VALIDATIONS=${MAX_HUBCLOUD_VALIDATIONS}
      - MAX_PACKS_TO_INSPECT=${MAX_PACKS_TO_INSPECT}
      - MAX_PACK_ROUNDS=${MAX_PACK_ROUNDS}
      - MAX_RESULTS_AUDIO=${MAX_RESULTS_AUDIO}
      - MAX_RESULTS_BLURAY=${MAX_RESULTS_BLURAY}
      - MAX_RESULTS_OTHER=${MAX_RESULTS_OTHER}
      - MAX_RESULTS_REMUX=${MAX_RESULTS_REMUX}
      - MAX_RESULTS_WEBDL=${MAX_RESULTS_WEBDL}
      - MAX_RESULTS_WEBRIP=${MAX_RESULTS_WEBRIP}
      - MAX_WORKERS=${MAX_WORKERS}
      - MONGO_CACHE_ENABLED=${MONGO_CACHE_ENABLED}
      - MONGO_URI=${MONGO_URI}
      - NO_CACHE=${NO_CACHE}
      - OFFCLOUD_API_KEY=${OFFCLOUD_API_KEY}
      - PORT=${PORT}
      - PREMIUMIZE_API_KEY=${PREMIUMIZE_API_KEY}
      - PRIORITY_SKIP_AAC_OPUS_ENABLED=${PRIORITY_SKIP_AAC_OPUS_ENABLED}
      - PRIORITY_SKIP_WEBRIP_ENABLED=${PRIORITY_SKIP_WEBRIP_ENABLED}
      - PTT_CACHE_LIMIT=${PTT_CACHE_LIMIT}
      - RD_API_KEY=${RD_API_KEY}
      - RD_CONCURRENCY=${RD_CONCURRENCY}
      - RD_DEBUG_LOGS=${RD_DEBUG_LOGS}
      - RD_MAX_RETRIES=${RD_MAX_RETRIES}
      - RD_PERSONAL_CACHE_TTL_MINUTES=${RD_PERSONAL_CACHE_TTL_MINUTES}
      - RD_RATE_PER_MINUTE=${RD_RATE_PER_MINUTE}
      - REQUEST_MAX_RETRIES=${REQUEST_MAX_RETRIES}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT}
      - SABNZBD_API_KEY=${SABNZBD_API_KEY}
      - SABNZBD_URL=${SABNZBD_URL}
      - SCRAPER_CACHE_LIMIT=${SCRAPER_CACHE_LIMIT}
      - SCRAPER_CACHE_TTL_MOVIE_MIN=${SCRAPER_CACHE_TTL_MOVIE_MIN}
      - SCRAPER_CACHE_TTL_SERIES_MIN=${SCRAPER_CACHE_TTL_SERIES_MIN}
      - SCRAPER_TIMEOUT=${SCRAPER_TIMEOUT}
      - SNOWFL_ENABLED=${SNOWFL_ENABLED}
      - SQLITE_CACHE_ENABLED=${SQLITE_CACHE_ENABLED}
      - SQLITE_CACHE_TTL_DAYS=${SQLITE_CACHE_TTL_DAYS}
      - SQLITE_DEBUG_LOGS=${SQLITE_DEBUG_LOGS}
      - STREMTHRU_ENABLED=${STREMTHRU_ENABLED}
      - STREMTHRU_URL=${STREMTHRU_URL}
      - TARGET_CODEC_COUNT=${TARGET_CODEC_COUNT}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - TMDB_FALLBACK_ENABLED=${TMDB_FALLBACK_ENABLED}
      - TORBOX_API_KEY=${TORBOX_API_KEY}
      - TORRENT9_ENABLED=${TORRENT9_ENABLED}
      - TORRENTDOWNLOAD_ENABLED=${TORRENTDOWNLOAD_ENABLED}
      - TORRENTDOWNLOAD_LIMIT=${TORRENTDOWNLOAD_LIMIT}
      - TORRENTDOWNLOAD_MAX_PAGES=${TORRENTDOWNLOAD_MAX_PAGES}
      - TORRENTDOWNLOAD_TIMEOUT=${TORRENTDOWNLOAD_TIMEOUT}
      - TORRENTDOWNLOAD_URL=${TORRENTDOWNLOAD_URL}
      - TORRENTIO_ENABLED=${TORRENTIO_ENABLED}
      - TORRENTIO_URL=${TORRENTIO_URL}
      - TORRENT_1337X_ENABLED=${TORRENT_1337X_ENABLED}
      - TORRENT_1337X_LIMIT=${TORRENT_1337X_LIMIT}
      - TORRENT_1337X_MAX_PAGES=${TORRENT_1337X_MAX_PAGES}
      - TORRENT_1337X_URL=${TORRENT_1337X_URL}
      - TORZNAB_LIMIT=${TORZNAB_LIMIT}
      - UHDMOVIES_ENABLED=${UHDMOVIES_ENABLED}
      - UHDMOVIES_PROXY_URL=${UHDMOVIES_PROXY_URL}
      - UHDMOVIES_REQUEST_TIMEOUT=${UHDMOVIES_REQUEST_TIMEOUT}
      - UHDMOVIES_VALIDATION_TIMEOUT=${UHDMOVIES_VALIDATION_TIMEOUT}
      - USENET_ENABLED=${USENET_ENABLED}
      - USENET_FILE_SERVER_API_KEY=${USENET_FILE_SERVER_API_KEY}
      - USENET_FILE_SERVER_URL=${USENET_FILE_SERVER_URL}
      - UV_THREADPOOL_SIZE=${UV_THREADPOOL_SIZE}
      - WOLFMAX4K_ENABLED=${WOLFMAX4K_ENABLED}
      - ZILEAN_ENABLED=${ZILEAN_ENABLED}
      - ZILEAN_LIMIT=${ZILEAN_LIMIT}
      - ZILEAN_URL=${ZILEAN_URL}
    command: ["node", "--max-old-space-size=12000", "--expose-gc", "server.js"]
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  sootio-data:

networks:
  proxy-net:
    external: true
